Document: morbid
Title: Debian morbid Manual
Author: <insert document author here>
Abstract: This manual describes what morbid is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/morbid/morbid.sgml.gz

Format: postscript
Files: /usr/share/doc/morbid/morbid.ps.gz

Format: text
Files: /usr/share/doc/morbid/morbid.text.gz

Format: HTML
Index: /usr/share/doc/morbid/html/index.html
Files: /usr/share/doc/morbid/html/*.html
